// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tictactoe.proto

package protogalaxy.tictactoe.proto;

public interface CreateReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tictactoe.CreateReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .tictactoe.CreateReply.ResponseStatus status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>optional .tictactoe.CreateReply.ResponseStatus status = 1;</code>
   */
  protogalaxy.tictactoe.proto.CreateReply.ResponseStatus getStatus();

  /**
   * <code>optional string game_id = 2;</code>
   */
  java.lang.String getGameId();
  /**
   * <code>optional string game_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getGameIdBytes();
}
