// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tictactoe.proto

package protogalaxy.tictactoe.proto;

/**
 * Protobuf type {@code tictactoe.CreateReply}
 */
public  final class CreateReply extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tictactoe.CreateReply)
    CreateReplyOrBuilder {
  // Use CreateReply.newBuilder() to construct.
  private CreateReply(com.google.protobuf.GeneratedMessage.Builder builder) {
    super(builder);
  }
  private CreateReply() {
    status_ = 0;
    gameId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CreateReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();

            gameId_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_CreateReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_CreateReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protogalaxy.tictactoe.proto.CreateReply.class, protogalaxy.tictactoe.proto.CreateReply.Builder.class);
  }

  public static final com.google.protobuf.Parser<CreateReply> PARSER =
      new com.google.protobuf.AbstractParser<CreateReply>() {
    public CreateReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateReply(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<CreateReply> getParserForType() {
    return PARSER;
  }

  /**
   * Protobuf enum {@code tictactoe.CreateReply.ResponseStatus}
   */
  public enum ResponseStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0, 0),
    UNRECOGNIZED(-1, -1),
    ;

    /**
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;


    public final int getNumber() {
      if (index == -1) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    public static ResponseStatus valueOf(int value) {
      switch (value) {
        case 0: return SUCCESS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponseStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ResponseStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseStatus>() {
            public ResponseStatus findValueByNumber(int number) {
              return ResponseStatus.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protogalaxy.tictactoe.proto.CreateReply.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResponseStatus[] VALUES = values();

    public static ResponseStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ResponseStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:tictactoe.CreateReply.ResponseStatus)
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>optional .tictactoe.CreateReply.ResponseStatus status = 1;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>optional .tictactoe.CreateReply.ResponseStatus status = 1;</code>
   */
  public protogalaxy.tictactoe.proto.CreateReply.ResponseStatus getStatus() {
    protogalaxy.tictactoe.proto.CreateReply.ResponseStatus result = protogalaxy.tictactoe.proto.CreateReply.ResponseStatus.valueOf(status_);
    return result == null ? protogalaxy.tictactoe.proto.CreateReply.ResponseStatus.UNRECOGNIZED : result;
  }

  public static final int GAME_ID_FIELD_NUMBER = 2;
  private java.lang.Object gameId_;
  /**
   * <code>optional string game_id = 2;</code>
   */
  public java.lang.String getGameId() {
    java.lang.Object ref = gameId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        gameId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string game_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getGameIdBytes() {
    java.lang.Object ref = gameId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (status_ != protogalaxy.tictactoe.proto.CreateReply.ResponseStatus.SUCCESS.getNumber()) {
      output.writeEnum(1, status_);
    }
    if (!getGameIdBytes().isEmpty()) {
      output.writeBytes(2, getGameIdBytes());
    }
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != protogalaxy.tictactoe.proto.CreateReply.ResponseStatus.SUCCESS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    if (!getGameIdBytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getGameIdBytes());
    }
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static protogalaxy.tictactoe.proto.CreateReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protogalaxy.tictactoe.proto.CreateReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.CreateReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protogalaxy.tictactoe.proto.CreateReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.CreateReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static protogalaxy.tictactoe.proto.CreateReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.CreateReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static protogalaxy.tictactoe.proto.CreateReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.CreateReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static protogalaxy.tictactoe.proto.CreateReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return new Builder(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(protogalaxy.tictactoe.proto.CreateReply prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tictactoe.CreateReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tictactoe.CreateReply)
      protogalaxy.tictactoe.proto.CreateReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_CreateReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_CreateReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protogalaxy.tictactoe.proto.CreateReply.class, protogalaxy.tictactoe.proto.CreateReply.Builder.class);
    }

    // Construct using protogalaxy.tictactoe.proto.CreateReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      status_ = 0;

      gameId_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_CreateReply_descriptor;
    }

    public protogalaxy.tictactoe.proto.CreateReply getDefaultInstanceForType() {
      return protogalaxy.tictactoe.proto.CreateReply.getDefaultInstance();
    }

    public protogalaxy.tictactoe.proto.CreateReply build() {
      protogalaxy.tictactoe.proto.CreateReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public protogalaxy.tictactoe.proto.CreateReply buildPartial() {
      protogalaxy.tictactoe.proto.CreateReply result = new protogalaxy.tictactoe.proto.CreateReply(this);
      result.status_ = status_;
      result.gameId_ = gameId_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protogalaxy.tictactoe.proto.CreateReply) {
        return mergeFrom((protogalaxy.tictactoe.proto.CreateReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protogalaxy.tictactoe.proto.CreateReply other) {
      if (other == protogalaxy.tictactoe.proto.CreateReply.getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.getGameId().isEmpty()) {
        gameId_ = other.gameId_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protogalaxy.tictactoe.proto.CreateReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protogalaxy.tictactoe.proto.CreateReply) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int status_ = 0;
    /**
     * <code>optional .tictactoe.CreateReply.ResponseStatus status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>optional .tictactoe.CreateReply.ResponseStatus status = 1;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .tictactoe.CreateReply.ResponseStatus status = 1;</code>
     */
    public protogalaxy.tictactoe.proto.CreateReply.ResponseStatus getStatus() {
      protogalaxy.tictactoe.proto.CreateReply.ResponseStatus result = protogalaxy.tictactoe.proto.CreateReply.ResponseStatus.valueOf(status_);
      return result == null ? protogalaxy.tictactoe.proto.CreateReply.ResponseStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .tictactoe.CreateReply.ResponseStatus status = 1;</code>
     */
    public Builder setStatus(protogalaxy.tictactoe.proto.CreateReply.ResponseStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .tictactoe.CreateReply.ResponseStatus status = 1;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object gameId_ = "";
    /**
     * <code>optional string game_id = 2;</code>
     */
    public java.lang.String getGameId() {
      java.lang.Object ref = gameId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gameId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string game_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGameIdBytes() {
      java.lang.Object ref = gameId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string game_id = 2;</code>
     */
    public Builder setGameId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gameId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string game_id = 2;</code>
     */
    public Builder clearGameId() {
      
      gameId_ = getDefaultInstance().getGameId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string game_id = 2;</code>
     */
    public Builder setGameIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gameId_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tictactoe.CreateReply)
  }

  // @@protoc_insertion_point(class_scope:tictactoe.CreateReply)
  private static final protogalaxy.tictactoe.proto.CreateReply defaultInstance;static {
    defaultInstance = new protogalaxy.tictactoe.proto.CreateReply();
  }

  public static protogalaxy.tictactoe.proto.CreateReply getDefaultInstance() {
    return defaultInstance;
  }

  public protogalaxy.tictactoe.proto.CreateReply getDefaultInstanceForType() {
    return defaultInstance;
  }

}

