// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tictactoe.proto

package protogalaxy.tictactoe.proto;

/**
 * Protobuf type {@code tictactoe.Event}
 */
public  final class Event extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tictactoe.Event)
    EventOrBuilder {
  // Use Event.newBuilder() to construct.
  private Event(com.google.protobuf.GeneratedMessage.Builder builder) {
    super(builder);
  }
  private Event() {
    type_ = 0;
    timestamp_ = 0L;
    gameId_ = "";
    userId_ = "";
    userList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    turnStatus_ = 0;
    moveId_ = 0L;
    nextPlayer_ = "";
    validMoves_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Event(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 16: {

            timestamp_ = input.readInt64();
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();

            gameId_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();

            userId_ = bs;
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              userList_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000010;
            }
            userList_.add(bs);
            break;
          }
          case 50: {
            protogalaxy.tictactoe.proto.TurnRequest.Square.Builder subBuilder = null;
            if (move_ != null) {
              subBuilder = move_.toBuilder();
            }
            move_ = input.readMessage(protogalaxy.tictactoe.proto.TurnRequest.Square.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(move_);
              move_ = subBuilder.buildPartial();
            }

            break;
          }
          case 56: {
            int rawValue = input.readEnum();

            turnStatus_ = rawValue;
            break;
          }
          case 66: {
            protogalaxy.tictactoe.proto.Winner.Builder subBuilder = null;
            if (winner_ != null) {
              subBuilder = winner_.toBuilder();
            }
            winner_ = input.readMessage(protogalaxy.tictactoe.proto.Winner.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(winner_);
              winner_ = subBuilder.buildPartial();
            }

            break;
          }
          case 72: {

            moveId_ = input.readInt64();
            break;
          }
          case 82: {
            com.google.protobuf.ByteString bs = input.readBytes();

            nextPlayer_ = bs;
            break;
          }
          case 90: {
            if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
              validMoves_ = new java.util.ArrayList<protogalaxy.tictactoe.proto.MoveRange>();
              mutable_bitField0_ |= 0x00000400;
            }
            validMoves_.add(input.readMessage(protogalaxy.tictactoe.proto.MoveRange.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        userList_ = userList_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
        validMoves_ = java.util.Collections.unmodifiableList(validMoves_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_Event_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_Event_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protogalaxy.tictactoe.proto.Event.class, protogalaxy.tictactoe.proto.Event.Builder.class);
  }

  public static final com.google.protobuf.Parser<Event> PARSER =
      new com.google.protobuf.AbstractParser<Event>() {
    public Event parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Event(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Event> getParserForType() {
    return PARSER;
  }

  /**
   * Protobuf enum {@code tictactoe.Event.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GAME_CREATED = 0;</code>
     */
    GAME_CREATED(0, 0),
    /**
     * <code>TURN_PLAYED = 1;</code>
     */
    TURN_PLAYED(1, 1),
    UNRECOGNIZED(-1, -1),
    ;

    /**
     * <code>GAME_CREATED = 0;</code>
     */
    public static final int GAME_CREATED_VALUE = 0;
    /**
     * <code>TURN_PLAYED = 1;</code>
     */
    public static final int TURN_PLAYED_VALUE = 1;


    public final int getNumber() {
      if (index == -1) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    public static Type valueOf(int value) {
      switch (value) {
        case 0: return GAME_CREATED;
        case 1: return TURN_PLAYED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protogalaxy.tictactoe.proto.Event.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Type(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:tictactoe.Event.Type)
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>optional .tictactoe.Event.Type type = 1;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>optional .tictactoe.Event.Type type = 1;</code>
   */
  public protogalaxy.tictactoe.proto.Event.Type getType() {
    protogalaxy.tictactoe.proto.Event.Type result = protogalaxy.tictactoe.proto.Event.Type.valueOf(type_);
    return result == null ? protogalaxy.tictactoe.proto.Event.Type.UNRECOGNIZED : result;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_;
  /**
   * <code>optional int64 timestamp = 2;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int GAME_ID_FIELD_NUMBER = 3;
  private java.lang.Object gameId_;
  /**
   * <code>optional string game_id = 3;</code>
   */
  public java.lang.String getGameId() {
    java.lang.Object ref = gameId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        gameId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string game_id = 3;</code>
   */
  public com.google.protobuf.ByteString
      getGameIdBytes() {
    java.lang.Object ref = gameId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_ID_FIELD_NUMBER = 4;
  private java.lang.Object userId_;
  /**
   * <code>optional string user_id = 4;</code>
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        userId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string user_id = 4;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_LIST_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList userList_;
  /**
   * <code>repeated string user_list = 5;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getUserListList() {
    return userList_;
  }
  /**
   * <code>repeated string user_list = 5;</code>
   */
  public int getUserListCount() {
    return userList_.size();
  }
  /**
   * <code>repeated string user_list = 5;</code>
   */
  public java.lang.String getUserList(int index) {
    return userList_.get(index);
  }
  /**
   * <code>repeated string user_list = 5;</code>
   */
  public com.google.protobuf.ByteString
      getUserListBytes(int index) {
    return userList_.getByteString(index);
  }

  public static final int MOVE_FIELD_NUMBER = 6;
  private protogalaxy.tictactoe.proto.TurnRequest.Square move_;
  /**
   * <code>optional .tictactoe.TurnRequest.Square move = 6;</code>
   */
  public boolean hasMove() {
    return move_ != null;
  }
  /**
   * <code>optional .tictactoe.TurnRequest.Square move = 6;</code>
   */
  public protogalaxy.tictactoe.proto.TurnRequest.Square getMove() {
    return move_ == null ? protogalaxy.tictactoe.proto.TurnRequest.Square.getDefaultInstance() : move_;
  }
  /**
   * <code>optional .tictactoe.TurnRequest.Square move = 6;</code>
   */
  public protogalaxy.tictactoe.proto.TurnRequest.SquareOrBuilder getMoveOrBuilder() {
    return getMove();
  }

  public static final int TURN_STATUS_FIELD_NUMBER = 7;
  private int turnStatus_;
  /**
   * <code>optional .tictactoe.TurnReply.ResponseStatus turn_status = 7;</code>
   */
  public int getTurnStatusValue() {
    return turnStatus_;
  }
  /**
   * <code>optional .tictactoe.TurnReply.ResponseStatus turn_status = 7;</code>
   */
  public protogalaxy.tictactoe.proto.TurnReply.ResponseStatus getTurnStatus() {
    protogalaxy.tictactoe.proto.TurnReply.ResponseStatus result = protogalaxy.tictactoe.proto.TurnReply.ResponseStatus.valueOf(turnStatus_);
    return result == null ? protogalaxy.tictactoe.proto.TurnReply.ResponseStatus.UNRECOGNIZED : result;
  }

  public static final int WINNER_FIELD_NUMBER = 8;
  private protogalaxy.tictactoe.proto.Winner winner_;
  /**
   * <code>optional .tictactoe.JsonWinner winner = 8;</code>
   */
  public boolean hasWinner() {
    return winner_ != null;
  }
  /**
   * <code>optional .tictactoe.JsonWinner winner = 8;</code>
   */
  public protogalaxy.tictactoe.proto.Winner getWinner() {
    return winner_ == null ? protogalaxy.tictactoe.proto.Winner.getDefaultInstance() : winner_;
  }
  /**
   * <code>optional .tictactoe.JsonWinner winner = 8;</code>
   */
  public protogalaxy.tictactoe.proto.WinnerOrBuilder getWinnerOrBuilder() {
    return getWinner();
  }

  public static final int MOVE_ID_FIELD_NUMBER = 9;
  private long moveId_;
  /**
   * <code>optional int64 move_id = 9;</code>
   */
  public long getMoveId() {
    return moveId_;
  }

  public static final int NEXT_PLAYER_FIELD_NUMBER = 10;
  private java.lang.Object nextPlayer_;
  /**
   * <code>optional string next_player = 10;</code>
   */
  public java.lang.String getNextPlayer() {
    java.lang.Object ref = nextPlayer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        nextPlayer_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string next_player = 10;</code>
   */
  public com.google.protobuf.ByteString
      getNextPlayerBytes() {
    java.lang.Object ref = nextPlayer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nextPlayer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALID_MOVES_FIELD_NUMBER = 11;
  private java.util.List<protogalaxy.tictactoe.proto.MoveRange> validMoves_;
  /**
   * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
   */
  public java.util.List<protogalaxy.tictactoe.proto.MoveRange> getValidMovesList() {
    return validMoves_;
  }
  /**
   * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
   */
  public java.util.List<? extends protogalaxy.tictactoe.proto.MoveRangeOrBuilder>
      getValidMovesOrBuilderList() {
    return validMoves_;
  }
  /**
   * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
   */
  public int getValidMovesCount() {
    return validMoves_.size();
  }
  /**
   * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
   */
  public protogalaxy.tictactoe.proto.MoveRange getValidMoves(int index) {
    return validMoves_.get(index);
  }
  /**
   * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
   */
  public protogalaxy.tictactoe.proto.MoveRangeOrBuilder getValidMovesOrBuilder(
      int index) {
    return validMoves_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (type_ != protogalaxy.tictactoe.proto.Event.Type.GAME_CREATED.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(2, timestamp_);
    }
    if (!getGameIdBytes().isEmpty()) {
      output.writeBytes(3, getGameIdBytes());
    }
    if (!getUserIdBytes().isEmpty()) {
      output.writeBytes(4, getUserIdBytes());
    }
    for (int i = 0; i < userList_.size(); i++) {
      output.writeBytes(5, userList_.getByteString(i));
    }
    if (move_ != null) {
      output.writeMessage(6, getMove());
    }
    if (turnStatus_ != protogalaxy.tictactoe.proto.TurnReply.ResponseStatus.SUCCESS.getNumber()) {
      output.writeEnum(7, turnStatus_);
    }
    if (winner_ != null) {
      output.writeMessage(8, getWinner());
    }
    if (moveId_ != 0L) {
      output.writeInt64(9, moveId_);
    }
    if (!getNextPlayerBytes().isEmpty()) {
      output.writeBytes(10, getNextPlayerBytes());
    }
    for (int i = 0; i < validMoves_.size(); i++) {
      output.writeMessage(11, validMoves_.get(i));
    }
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != protogalaxy.tictactoe.proto.Event.Type.GAME_CREATED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timestamp_);
    }
    if (!getGameIdBytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getGameIdBytes());
    }
    if (!getUserIdBytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, getUserIdBytes());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < userList_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(userList_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getUserListList().size();
    }
    if (move_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getMove());
    }
    if (turnStatus_ != protogalaxy.tictactoe.proto.TurnReply.ResponseStatus.SUCCESS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, turnStatus_);
    }
    if (winner_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getWinner());
    }
    if (moveId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, moveId_);
    }
    if (!getNextPlayerBytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(10, getNextPlayerBytes());
    }
    for (int i = 0; i < validMoves_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, validMoves_.get(i));
    }
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static protogalaxy.tictactoe.proto.Event parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protogalaxy.tictactoe.proto.Event parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.Event parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protogalaxy.tictactoe.proto.Event parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.Event parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static protogalaxy.tictactoe.proto.Event parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.Event parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static protogalaxy.tictactoe.proto.Event parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.Event parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static protogalaxy.tictactoe.proto.Event parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return new Builder(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(protogalaxy.tictactoe.proto.Event prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tictactoe.Event}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tictactoe.Event)
      protogalaxy.tictactoe.proto.EventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_Event_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protogalaxy.tictactoe.proto.Event.class, protogalaxy.tictactoe.proto.Event.Builder.class);
    }

    // Construct using protogalaxy.tictactoe.proto.Event.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getValidMovesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      type_ = 0;

      timestamp_ = 0L;

      gameId_ = "";

      userId_ = "";

      userList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      if (moveBuilder_ == null) {
        move_ = null;
      } else {
        move_ = null;
        moveBuilder_ = null;
      }
      turnStatus_ = 0;

      if (winnerBuilder_ == null) {
        winner_ = null;
      } else {
        winner_ = null;
        winnerBuilder_ = null;
      }
      moveId_ = 0L;

      nextPlayer_ = "";

      if (validMovesBuilder_ == null) {
        validMoves_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000400);
      } else {
        validMovesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_Event_descriptor;
    }

    public protogalaxy.tictactoe.proto.Event getDefaultInstanceForType() {
      return protogalaxy.tictactoe.proto.Event.getDefaultInstance();
    }

    public protogalaxy.tictactoe.proto.Event build() {
      protogalaxy.tictactoe.proto.Event result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public protogalaxy.tictactoe.proto.Event buildPartial() {
      protogalaxy.tictactoe.proto.Event result = new protogalaxy.tictactoe.proto.Event(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.type_ = type_;
      result.timestamp_ = timestamp_;
      result.gameId_ = gameId_;
      result.userId_ = userId_;
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        userList_ = userList_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.userList_ = userList_;
      if (moveBuilder_ == null) {
        result.move_ = move_;
      } else {
        result.move_ = moveBuilder_.build();
      }
      result.turnStatus_ = turnStatus_;
      if (winnerBuilder_ == null) {
        result.winner_ = winner_;
      } else {
        result.winner_ = winnerBuilder_.build();
      }
      result.moveId_ = moveId_;
      result.nextPlayer_ = nextPlayer_;
      if (validMovesBuilder_ == null) {
        if (((bitField0_ & 0x00000400) == 0x00000400)) {
          validMoves_ = java.util.Collections.unmodifiableList(validMoves_);
          bitField0_ = (bitField0_ & ~0x00000400);
        }
        result.validMoves_ = validMoves_;
      } else {
        result.validMoves_ = validMovesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protogalaxy.tictactoe.proto.Event) {
        return mergeFrom((protogalaxy.tictactoe.proto.Event)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protogalaxy.tictactoe.proto.Event other) {
      if (other == protogalaxy.tictactoe.proto.Event.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (!other.getGameId().isEmpty()) {
        gameId_ = other.gameId_;
        onChanged();
      }
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (!other.userList_.isEmpty()) {
        if (userList_.isEmpty()) {
          userList_ = other.userList_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureUserListIsMutable();
          userList_.addAll(other.userList_);
        }
        onChanged();
      }
      if (other.hasMove()) {
        mergeMove(other.getMove());
      }
      if (other.turnStatus_ != 0) {
        setTurnStatusValue(other.getTurnStatusValue());
      }
      if (other.hasWinner()) {
        mergeWinner(other.getWinner());
      }
      if (other.getMoveId() != 0L) {
        setMoveId(other.getMoveId());
      }
      if (!other.getNextPlayer().isEmpty()) {
        nextPlayer_ = other.nextPlayer_;
        onChanged();
      }
      if (validMovesBuilder_ == null) {
        if (!other.validMoves_.isEmpty()) {
          if (validMoves_.isEmpty()) {
            validMoves_ = other.validMoves_;
            bitField0_ = (bitField0_ & ~0x00000400);
          } else {
            ensureValidMovesIsMutable();
            validMoves_.addAll(other.validMoves_);
          }
          onChanged();
        }
      } else {
        if (!other.validMoves_.isEmpty()) {
          if (validMovesBuilder_.isEmpty()) {
            validMovesBuilder_.dispose();
            validMovesBuilder_ = null;
            validMoves_ = other.validMoves_;
            bitField0_ = (bitField0_ & ~0x00000400);
            validMovesBuilder_ =
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getValidMovesFieldBuilder() : null;
          } else {
            validMovesBuilder_.addAllMessages(other.validMoves_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protogalaxy.tictactoe.proto.Event parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protogalaxy.tictactoe.proto.Event) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>optional .tictactoe.Event.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .tictactoe.Event.Type type = 1;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .tictactoe.Event.Type type = 1;</code>
     */
    public protogalaxy.tictactoe.proto.Event.Type getType() {
      protogalaxy.tictactoe.proto.Event.Type result = protogalaxy.tictactoe.proto.Event.Type.valueOf(type_);
      return result == null ? protogalaxy.tictactoe.proto.Event.Type.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .tictactoe.Event.Type type = 1;</code>
     */
    public Builder setType(protogalaxy.tictactoe.proto.Event.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }

      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .tictactoe.Event.Type type = 1;</code>
     */
    public Builder clearType() {

      type_ = 0;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    public Builder clearTimestamp() {

      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object gameId_ = "";
    /**
     * <code>optional string game_id = 3;</code>
     */
    public java.lang.String getGameId() {
      java.lang.Object ref = gameId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gameId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string game_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGameIdBytes() {
      java.lang.Object ref = gameId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string game_id = 3;</code>
     */
    public Builder setGameId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      gameId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string game_id = 3;</code>
     */
    public Builder clearGameId() {

      gameId_ = getDefaultInstance().getGameId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string game_id = 3;</code>
     */
    public Builder setGameIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      gameId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <code>optional string user_id = 4;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string user_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string user_id = 4;</code>
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string user_id = 4;</code>
     */
    public Builder clearUserId() {

      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string user_id = 4;</code>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      userId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList userList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureUserListIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        userList_ = new com.google.protobuf.LazyStringArrayList(userList_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <code>repeated string user_list = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getUserListList() {
      return userList_.getUnmodifiableView();
    }
    /**
     * <code>repeated string user_list = 5;</code>
     */
    public int getUserListCount() {
      return userList_.size();
    }
    /**
     * <code>repeated string user_list = 5;</code>
     */
    public java.lang.String getUserList(int index) {
      return userList_.get(index);
    }
    /**
     * <code>repeated string user_list = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserListBytes(int index) {
      return userList_.getByteString(index);
    }
    /**
     * <code>repeated string user_list = 5;</code>
     */
    public Builder setUserList(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUserListIsMutable();
      userList_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string user_list = 5;</code>
     */
    public Builder addUserList(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUserListIsMutable();
      userList_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string user_list = 5;</code>
     */
    public Builder addAllUserList(
        java.lang.Iterable<java.lang.String> values) {
      ensureUserListIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, userList_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string user_list = 5;</code>
     */
    public Builder clearUserList() {
      userList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string user_list = 5;</code>
     */
    public Builder addUserListBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUserListIsMutable();
      userList_.add(value);
      onChanged();
      return this;
    }

    private protogalaxy.tictactoe.proto.TurnRequest.Square move_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        protogalaxy.tictactoe.proto.TurnRequest.Square, protogalaxy.tictactoe.proto.TurnRequest.Square.Builder, protogalaxy.tictactoe.proto.TurnRequest.SquareOrBuilder> moveBuilder_;
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 6;</code>
     */
    public boolean hasMove() {
      return moveBuilder_ != null || move_ != null;
    }
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 6;</code>
     */
    public protogalaxy.tictactoe.proto.TurnRequest.Square getMove() {
      if (moveBuilder_ == null) {
        return move_ == null ? protogalaxy.tictactoe.proto.TurnRequest.Square.getDefaultInstance() : move_;
      } else {
        return moveBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 6;</code>
     */
    public Builder setMove(protogalaxy.tictactoe.proto.TurnRequest.Square value) {
      if (moveBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        move_ = value;
        onChanged();
      } else {
        moveBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 6;</code>
     */
    public Builder setMove(
        protogalaxy.tictactoe.proto.TurnRequest.Square.Builder builderForValue) {
      if (moveBuilder_ == null) {
        move_ = builderForValue.build();
        onChanged();
      } else {
        moveBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 6;</code>
     */
    public Builder mergeMove(protogalaxy.tictactoe.proto.TurnRequest.Square value) {
      if (moveBuilder_ == null) {
        if (move_ != null) {
          move_ =
            protogalaxy.tictactoe.proto.TurnRequest.Square.newBuilder(move_).mergeFrom(value).buildPartial();
        } else {
          move_ = value;
        }
        onChanged();
      } else {
        moveBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 6;</code>
     */
    public Builder clearMove() {
      if (moveBuilder_ == null) {
        move_ = null;
        onChanged();
      } else {
        move_ = null;
        moveBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 6;</code>
     */
    public protogalaxy.tictactoe.proto.TurnRequest.Square.Builder getMoveBuilder() {

      onChanged();
      return getMoveFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 6;</code>
     */
    public protogalaxy.tictactoe.proto.TurnRequest.SquareOrBuilder getMoveOrBuilder() {
      if (moveBuilder_ != null) {
        return moveBuilder_.getMessageOrBuilder();
      } else {
        return move_ == null ?
            protogalaxy.tictactoe.proto.TurnRequest.Square.getDefaultInstance() : move_;
      }
    }
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        protogalaxy.tictactoe.proto.TurnRequest.Square, protogalaxy.tictactoe.proto.TurnRequest.Square.Builder, protogalaxy.tictactoe.proto.TurnRequest.SquareOrBuilder>
        getMoveFieldBuilder() {
      if (moveBuilder_ == null) {
        moveBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            protogalaxy.tictactoe.proto.TurnRequest.Square, protogalaxy.tictactoe.proto.TurnRequest.Square.Builder, protogalaxy.tictactoe.proto.TurnRequest.SquareOrBuilder>(
                getMove(),
                getParentForChildren(),
                isClean());
        move_ = null;
      }
      return moveBuilder_;
    }

    private int turnStatus_ = 0;
    /**
     * <code>optional .tictactoe.TurnReply.ResponseStatus turn_status = 7;</code>
     */
    public int getTurnStatusValue() {
      return turnStatus_;
    }
    /**
     * <code>optional .tictactoe.TurnReply.ResponseStatus turn_status = 7;</code>
     */
    public Builder setTurnStatusValue(int value) {
      turnStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .tictactoe.TurnReply.ResponseStatus turn_status = 7;</code>
     */
    public protogalaxy.tictactoe.proto.TurnReply.ResponseStatus getTurnStatus() {
      protogalaxy.tictactoe.proto.TurnReply.ResponseStatus result = protogalaxy.tictactoe.proto.TurnReply.ResponseStatus.valueOf(turnStatus_);
      return result == null ? protogalaxy.tictactoe.proto.TurnReply.ResponseStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .tictactoe.TurnReply.ResponseStatus turn_status = 7;</code>
     */
    public Builder setTurnStatus(protogalaxy.tictactoe.proto.TurnReply.ResponseStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }

      turnStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .tictactoe.TurnReply.ResponseStatus turn_status = 7;</code>
     */
    public Builder clearTurnStatus() {

      turnStatus_ = 0;
      onChanged();
      return this;
    }

    private protogalaxy.tictactoe.proto.Winner winner_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        protogalaxy.tictactoe.proto.Winner, protogalaxy.tictactoe.proto.Winner.Builder, protogalaxy.tictactoe.proto.WinnerOrBuilder> winnerBuilder_;
    /**
     * <code>optional .tictactoe.JsonWinner winner = 8;</code>
     */
    public boolean hasWinner() {
      return winnerBuilder_ != null || winner_ != null;
    }
    /**
     * <code>optional .tictactoe.JsonWinner winner = 8;</code>
     */
    public protogalaxy.tictactoe.proto.Winner getWinner() {
      if (winnerBuilder_ == null) {
        return winner_ == null ? protogalaxy.tictactoe.proto.Winner.getDefaultInstance() : winner_;
      } else {
        return winnerBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .tictactoe.JsonWinner winner = 8;</code>
     */
    public Builder setWinner(protogalaxy.tictactoe.proto.Winner value) {
      if (winnerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        winner_ = value;
        onChanged();
      } else {
        winnerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .tictactoe.JsonWinner winner = 8;</code>
     */
    public Builder setWinner(
        protogalaxy.tictactoe.proto.Winner.Builder builderForValue) {
      if (winnerBuilder_ == null) {
        winner_ = builderForValue.build();
        onChanged();
      } else {
        winnerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .tictactoe.JsonWinner winner = 8;</code>
     */
    public Builder mergeWinner(protogalaxy.tictactoe.proto.Winner value) {
      if (winnerBuilder_ == null) {
        if (winner_ != null) {
          winner_ =
            protogalaxy.tictactoe.proto.Winner.newBuilder(winner_).mergeFrom(value).buildPartial();
        } else {
          winner_ = value;
        }
        onChanged();
      } else {
        winnerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .tictactoe.JsonWinner winner = 8;</code>
     */
    public Builder clearWinner() {
      if (winnerBuilder_ == null) {
        winner_ = null;
        onChanged();
      } else {
        winner_ = null;
        winnerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .tictactoe.JsonWinner winner = 8;</code>
     */
    public protogalaxy.tictactoe.proto.Winner.Builder getWinnerBuilder() {

      onChanged();
      return getWinnerFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .tictactoe.JsonWinner winner = 8;</code>
     */
    public protogalaxy.tictactoe.proto.WinnerOrBuilder getWinnerOrBuilder() {
      if (winnerBuilder_ != null) {
        return winnerBuilder_.getMessageOrBuilder();
      } else {
        return winner_ == null ?
            protogalaxy.tictactoe.proto.Winner.getDefaultInstance() : winner_;
      }
    }
    /**
     * <code>optional .tictactoe.JsonWinner winner = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        protogalaxy.tictactoe.proto.Winner, protogalaxy.tictactoe.proto.Winner.Builder, protogalaxy.tictactoe.proto.WinnerOrBuilder>
        getWinnerFieldBuilder() {
      if (winnerBuilder_ == null) {
        winnerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            protogalaxy.tictactoe.proto.Winner, protogalaxy.tictactoe.proto.Winner.Builder, protogalaxy.tictactoe.proto.WinnerOrBuilder>(
                getWinner(),
                getParentForChildren(),
                isClean());
        winner_ = null;
      }
      return winnerBuilder_;
    }

    private long moveId_ ;
    /**
     * <code>optional int64 move_id = 9;</code>
     */
    public long getMoveId() {
      return moveId_;
    }
    /**
     * <code>optional int64 move_id = 9;</code>
     */
    public Builder setMoveId(long value) {

      moveId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 move_id = 9;</code>
     */
    public Builder clearMoveId() {

      moveId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object nextPlayer_ = "";
    /**
     * <code>optional string next_player = 10;</code>
     */
    public java.lang.String getNextPlayer() {
      java.lang.Object ref = nextPlayer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nextPlayer_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string next_player = 10;</code>
     */
    public com.google.protobuf.ByteString
        getNextPlayerBytes() {
      java.lang.Object ref = nextPlayer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nextPlayer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string next_player = 10;</code>
     */
    public Builder setNextPlayer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      nextPlayer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string next_player = 10;</code>
     */
    public Builder clearNextPlayer() {

      nextPlayer_ = getDefaultInstance().getNextPlayer();
      onChanged();
      return this;
    }
    /**
     * <code>optional string next_player = 10;</code>
     */
    public Builder setNextPlayerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      nextPlayer_ = value;
      onChanged();
      return this;
    }

    private java.util.List<protogalaxy.tictactoe.proto.MoveRange> validMoves_ =
      java.util.Collections.emptyList();
    private void ensureValidMovesIsMutable() {
      if (!((bitField0_ & 0x00000400) == 0x00000400)) {
        validMoves_ = new java.util.ArrayList<protogalaxy.tictactoe.proto.MoveRange>(validMoves_);
        bitField0_ |= 0x00000400;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        protogalaxy.tictactoe.proto.MoveRange, protogalaxy.tictactoe.proto.MoveRange.Builder, protogalaxy.tictactoe.proto.MoveRangeOrBuilder> validMovesBuilder_;

    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public java.util.List<protogalaxy.tictactoe.proto.MoveRange> getValidMovesList() {
      if (validMovesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(validMoves_);
      } else {
        return validMovesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public int getValidMovesCount() {
      if (validMovesBuilder_ == null) {
        return validMoves_.size();
      } else {
        return validMovesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public protogalaxy.tictactoe.proto.MoveRange getValidMoves(int index) {
      if (validMovesBuilder_ == null) {
        return validMoves_.get(index);
      } else {
        return validMovesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public Builder setValidMoves(
        int index, protogalaxy.tictactoe.proto.MoveRange value) {
      if (validMovesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValidMovesIsMutable();
        validMoves_.set(index, value);
        onChanged();
      } else {
        validMovesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public Builder setValidMoves(
        int index, protogalaxy.tictactoe.proto.MoveRange.Builder builderForValue) {
      if (validMovesBuilder_ == null) {
        ensureValidMovesIsMutable();
        validMoves_.set(index, builderForValue.build());
        onChanged();
      } else {
        validMovesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public Builder addValidMoves(protogalaxy.tictactoe.proto.MoveRange value) {
      if (validMovesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValidMovesIsMutable();
        validMoves_.add(value);
        onChanged();
      } else {
        validMovesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public Builder addValidMoves(
        int index, protogalaxy.tictactoe.proto.MoveRange value) {
      if (validMovesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValidMovesIsMutable();
        validMoves_.add(index, value);
        onChanged();
      } else {
        validMovesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public Builder addValidMoves(
        protogalaxy.tictactoe.proto.MoveRange.Builder builderForValue) {
      if (validMovesBuilder_ == null) {
        ensureValidMovesIsMutable();
        validMoves_.add(builderForValue.build());
        onChanged();
      } else {
        validMovesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public Builder addValidMoves(
        int index, protogalaxy.tictactoe.proto.MoveRange.Builder builderForValue) {
      if (validMovesBuilder_ == null) {
        ensureValidMovesIsMutable();
        validMoves_.add(index, builderForValue.build());
        onChanged();
      } else {
        validMovesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public Builder addAllValidMoves(
        java.lang.Iterable<? extends protogalaxy.tictactoe.proto.MoveRange> values) {
      if (validMovesBuilder_ == null) {
        ensureValidMovesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, validMoves_);
        onChanged();
      } else {
        validMovesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public Builder clearValidMoves() {
      if (validMovesBuilder_ == null) {
        validMoves_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
      } else {
        validMovesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public Builder removeValidMoves(int index) {
      if (validMovesBuilder_ == null) {
        ensureValidMovesIsMutable();
        validMoves_.remove(index);
        onChanged();
      } else {
        validMovesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public protogalaxy.tictactoe.proto.MoveRange.Builder getValidMovesBuilder(
        int index) {
      return getValidMovesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public protogalaxy.tictactoe.proto.MoveRangeOrBuilder getValidMovesOrBuilder(
        int index) {
      if (validMovesBuilder_ == null) {
        return validMoves_.get(index);  } else {
        return validMovesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public java.util.List<? extends protogalaxy.tictactoe.proto.MoveRangeOrBuilder>
         getValidMovesOrBuilderList() {
      if (validMovesBuilder_ != null) {
        return validMovesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(validMoves_);
      }
    }
    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public protogalaxy.tictactoe.proto.MoveRange.Builder addValidMovesBuilder() {
      return getValidMovesFieldBuilder().addBuilder(
          protogalaxy.tictactoe.proto.MoveRange.getDefaultInstance());
    }
    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public protogalaxy.tictactoe.proto.MoveRange.Builder addValidMovesBuilder(
        int index) {
      return getValidMovesFieldBuilder().addBuilder(
          index, protogalaxy.tictactoe.proto.MoveRange.getDefaultInstance());
    }
    /**
     * <code>repeated .tictactoe.JsonMoveRange valid_moves = 11;</code>
     */
    public java.util.List<protogalaxy.tictactoe.proto.MoveRange.Builder>
         getValidMovesBuilderList() {
      return getValidMovesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        protogalaxy.tictactoe.proto.MoveRange, protogalaxy.tictactoe.proto.MoveRange.Builder, protogalaxy.tictactoe.proto.MoveRangeOrBuilder>
        getValidMovesFieldBuilder() {
      if (validMovesBuilder_ == null) {
        validMovesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            protogalaxy.tictactoe.proto.MoveRange, protogalaxy.tictactoe.proto.MoveRange.Builder, protogalaxy.tictactoe.proto.MoveRangeOrBuilder>(
                validMoves_,
                ((bitField0_ & 0x00000400) == 0x00000400),
                getParentForChildren(),
                isClean());
        validMoves_ = null;
      }
      return validMovesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tictactoe.Event)
  }

  // @@protoc_insertion_point(class_scope:tictactoe.Event)
  private static final protogalaxy.tictactoe.proto.Event defaultInstance;static {
    defaultInstance = new protogalaxy.tictactoe.proto.Event();
  }

  public static protogalaxy.tictactoe.proto.Event getDefaultInstance() {
    return defaultInstance;
  }

  public protogalaxy.tictactoe.proto.Event getDefaultInstanceForType() {
    return defaultInstance;
  }

}

