// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tictactoe.proto

package protogalaxy.tictactoe.proto;

public interface MoveRangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tictactoe.JsonMoveRange)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 from_x = 1;</code>
   */
  int getFromX();

  /**
   * <code>optional int32 from_y = 2;</code>
   */
  int getFromY();

  /**
   * <code>optional int32 to_x = 3;</code>
   */
  int getToX();

  /**
   * <code>optional int32 to_y = 4;</code>
   */
  int getToY();
}
