// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tictactoe.proto

package protogalaxy.tictactoe.proto;

public final class Tictactoe {
  private Tictactoe() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tictactoe_CreateReply_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tictactoe_CreateReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tictactoe_TurnRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tictactoe_TurnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tictactoe_TurnRequest_Square_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tictactoe_TurnRequest_Square_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tictactoe_Winner_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tictactoe_Winner_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tictactoe_Winner_Location_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tictactoe_Winner_Location_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tictactoe_TurnReply_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tictactoe_TurnReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tictactoe_MoveRange_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tictactoe_MoveRange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tictactoe_Event_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tictactoe_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017tictactoe.proto\022\ttictactoe\"t\n\013CreateRe" +
      "ply\0225\n\006status\030\001 \001(\0162%.tictactoe.CreateRe" +
      "ply.ResponseStatus\022\017\n\007game_id\030\002 \001(\t\"\035\n\016R" +
      "esponseStatus\022\013\n\007SUCCESS\020\000\"\215\001\n\013TurnReque" +
      "st\022\017\n\007game_id\030\001 \001(\t\022\017\n\007user_id\030\002 \001(\t\022\017\n\007" +
      "move_id\030\003 \001(\003\022+\n\004move\030\004 \001(\0132\035.tictactoe." +
      "TurnRequest.Square\032\036\n\006Square\022\t\n\001x\030\001 \001(\005\022" +
      "\t\n\001y\030\002 \001(\005\"\222\002\n\006Winner\022\016\n\004draw\030\001 \001(\010H\000\022\021\n" +
      "\007user_id\030\002 \001(\tH\000\022-\n\tlocations\030\003 \003(\0132\032.ti" +
      "ctactoe.JsonWinner.JsonLocation\032\244\001\n\010Location\0227\n\t",
      "direction\030\001 \001(\0162$.tictactoe.JsonWinner.Locat" +
      "ion.Direction\022\020\n\010position\030\002 \001(\005\"M\n\tDirec" +
      "tion\022\016\n\nHORIZONTAL\020\000\022\014\n\010VERTICAL\020\001\022\021\n\rDI" +
      "AGONAL_DOWN\020\002\022\017\n\013DIAGONAL_UP\020\003B\017\n\rwinner" +
      "_status\"\274\001\n\tTurnReply\0223\n\006status\030\001 \001(\0162#." +
      "tictactoe.TurnReply.ResponseStatus\022\017\n\007mo" +
      "ve_id\030\002 \001(\003\"i\n\016ResponseStatus\022\013\n\007SUCCESS" +
      "\020\000\022\020\n\014INVALID_MOVE\020\001\022\025\n\021NOT_ACTIVE_PLAYE" +
      "R\020\002\022\014\n\010FINISHED\020\003\022\023\n\017INVALID_MOVE_ID\020\004\"G" +
      "\n\tJsonMoveRange\022\016\n\006from_x\030\001 \001(\005\022\016\n\006from_y\030\002 ",
      "\001(\005\022\014\n\004to_x\030\003 \001(\005\022\014\n\004to_y\030\004 \001(\005\"\372\002\n\005Even" +
      "t\022#\n\004type\030\001 \001(\0162\025.tictactoe.Event.Type\022\021" +
      "\n\ttimestamp\030\002 \001(\003\022\017\n\007game_id\030\003 \001(\t\022\017\n\007us" +
      "er_id\030\004 \001(\t\022\021\n\tuser_list\030\005 \003(\t\022+\n\004move\030\006" +
      " \001(\0132\035.tictactoe.TurnRequest.Square\0228\n\013t" +
      "urn_status\030\007 \001(\0162#.tictactoe.TurnReply.R" +
      "esponseStatus\022!\n\006winner\030\010 \001(\0132\021.tictacto" +
      "e.JsonWinner\022\017\n\007move_id\030\t \001(\003\022\023\n\013next_player" +
      "\030\n \001(\t\022)\n\013valid_moves\030\013 \003(\0132\024.tictactoe." +
      "JsonMoveRange\")\n\004Type\022\020\n\014GAME_CREATED\020\000\022\017\n\013T",
      "URN_PLAYED\020\001*\037\n\004Mark\022\t\n\005EMPTY\020\000\022\005\n\001X\020\001\022\005" +
      "\n\001Y\020\002B\037\n\033protogalaxy.tictactoe.protoP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tictactoe_CreateReply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tictactoe_CreateReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tictactoe_CreateReply_descriptor,
        new java.lang.String[] { "Status", "GameId", });
    internal_static_tictactoe_TurnRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tictactoe_TurnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tictactoe_TurnRequest_descriptor,
        new java.lang.String[] { "GameId", "UserId", "MoveId", "Move", });
    internal_static_tictactoe_TurnRequest_Square_descriptor =
      internal_static_tictactoe_TurnRequest_descriptor.getNestedTypes().get(0);
    internal_static_tictactoe_TurnRequest_Square_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tictactoe_TurnRequest_Square_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_tictactoe_Winner_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tictactoe_Winner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tictactoe_Winner_descriptor,
        new java.lang.String[] { "Draw", "UserId", "Locations", "WinnerStatus", });
    internal_static_tictactoe_Winner_Location_descriptor =
      internal_static_tictactoe_Winner_descriptor.getNestedTypes().get(0);
    internal_static_tictactoe_Winner_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tictactoe_Winner_Location_descriptor,
        new java.lang.String[] { "Direction", "Position", });
    internal_static_tictactoe_TurnReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tictactoe_TurnReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tictactoe_TurnReply_descriptor,
        new java.lang.String[] { "Status", "MoveId", });
    internal_static_tictactoe_MoveRange_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tictactoe_MoveRange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tictactoe_MoveRange_descriptor,
        new java.lang.String[] { "FromX", "FromY", "ToX", "ToY", });
    internal_static_tictactoe_Event_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tictactoe_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tictactoe_Event_descriptor,
        new java.lang.String[] { "Type", "Timestamp", "GameId", "UserId", "UserList", "Move", "TurnStatus", "JsonWinner", "MoveId", "NextPlayer", "ValidMoves", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
