// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tictactoe.proto

package protogalaxy.tictactoe.proto;

public interface TurnReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tictactoe.TurnReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .tictactoe.TurnReply.ResponseStatus status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>optional .tictactoe.TurnReply.ResponseStatus status = 1;</code>
   */
  protogalaxy.tictactoe.proto.TurnReply.ResponseStatus getStatus();

  /**
   * <code>optional int64 move_id = 2;</code>
   */
  long getMoveId();
}
