// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tictactoe.proto

package protogalaxy.tictactoe.proto;

public interface TurnRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tictactoe.TurnRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string game_id = 1;</code>
   */
  java.lang.String getGameId();
  /**
   * <code>optional string game_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getGameIdBytes();

  /**
   * <code>optional string user_id = 2;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>optional string user_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>optional int64 move_id = 3;</code>
   */
  long getMoveId();

  /**
   * <code>optional .tictactoe.TurnRequest.Square move = 4;</code>
   */
  boolean hasMove();
  /**
   * <code>optional .tictactoe.TurnRequest.Square move = 4;</code>
   */
  protogalaxy.tictactoe.proto.TurnRequest.Square getMove();
  /**
   * <code>optional .tictactoe.TurnRequest.Square move = 4;</code>
   */
  protogalaxy.tictactoe.proto.TurnRequest.SquareOrBuilder getMoveOrBuilder();
}
