// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tictactoe.proto

package protogalaxy.tictactoe.proto;

/**
 * Protobuf type {@code tictactoe.TurnReply}
 */
public  final class TurnReply extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tictactoe.TurnReply)
    TurnReplyOrBuilder {
  // Use TurnReply.newBuilder() to construct.
  private TurnReply(com.google.protobuf.GeneratedMessage.Builder builder) {
    super(builder);
  }
  private TurnReply() {
    status_ = 0;
    moveId_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TurnReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 16: {

            moveId_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_TurnReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_TurnReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protogalaxy.tictactoe.proto.TurnReply.class, protogalaxy.tictactoe.proto.TurnReply.Builder.class);
  }

  public static final com.google.protobuf.Parser<TurnReply> PARSER =
      new com.google.protobuf.AbstractParser<TurnReply>() {
    public TurnReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TurnReply(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<TurnReply> getParserForType() {
    return PARSER;
  }

  /**
   * Protobuf enum {@code tictactoe.TurnReply.ResponseStatus}
   */
  public enum ResponseStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0, 0),
    /**
     * <code>INVALID_MOVE = 1;</code>
     */
    INVALID_MOVE(1, 1),
    /**
     * <code>NOT_ACTIVE_PLAYER = 2;</code>
     */
    NOT_ACTIVE_PLAYER(2, 2),
    /**
     * <code>FINISHED = 3;</code>
     */
    FINISHED(3, 3),
    /**
     * <code>INVALID_MOVE_ID = 4;</code>
     */
    INVALID_MOVE_ID(4, 4),
    UNRECOGNIZED(-1, -1),
    ;

    /**
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <code>INVALID_MOVE = 1;</code>
     */
    public static final int INVALID_MOVE_VALUE = 1;
    /**
     * <code>NOT_ACTIVE_PLAYER = 2;</code>
     */
    public static final int NOT_ACTIVE_PLAYER_VALUE = 2;
    /**
     * <code>FINISHED = 3;</code>
     */
    public static final int FINISHED_VALUE = 3;
    /**
     * <code>INVALID_MOVE_ID = 4;</code>
     */
    public static final int INVALID_MOVE_ID_VALUE = 4;


    public final int getNumber() {
      if (index == -1) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    public static ResponseStatus valueOf(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return INVALID_MOVE;
        case 2: return NOT_ACTIVE_PLAYER;
        case 3: return FINISHED;
        case 4: return INVALID_MOVE_ID;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponseStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ResponseStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseStatus>() {
            public ResponseStatus findValueByNumber(int number) {
              return ResponseStatus.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protogalaxy.tictactoe.proto.TurnReply.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResponseStatus[] VALUES = values();

    public static ResponseStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ResponseStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:tictactoe.TurnReply.ResponseStatus)
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>optional .tictactoe.TurnReply.ResponseStatus status = 1;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>optional .tictactoe.TurnReply.ResponseStatus status = 1;</code>
   */
  public protogalaxy.tictactoe.proto.TurnReply.ResponseStatus getStatus() {
    protogalaxy.tictactoe.proto.TurnReply.ResponseStatus result = protogalaxy.tictactoe.proto.TurnReply.ResponseStatus.valueOf(status_);
    return result == null ? protogalaxy.tictactoe.proto.TurnReply.ResponseStatus.UNRECOGNIZED : result;
  }

  public static final int MOVE_ID_FIELD_NUMBER = 2;
  private long moveId_;
  /**
   * <code>optional int64 move_id = 2;</code>
   */
  public long getMoveId() {
    return moveId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (status_ != protogalaxy.tictactoe.proto.TurnReply.ResponseStatus.SUCCESS.getNumber()) {
      output.writeEnum(1, status_);
    }
    if (moveId_ != 0L) {
      output.writeInt64(2, moveId_);
    }
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != protogalaxy.tictactoe.proto.TurnReply.ResponseStatus.SUCCESS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    if (moveId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, moveId_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static protogalaxy.tictactoe.proto.TurnReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protogalaxy.tictactoe.proto.TurnReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.TurnReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protogalaxy.tictactoe.proto.TurnReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.TurnReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static protogalaxy.tictactoe.proto.TurnReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.TurnReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static protogalaxy.tictactoe.proto.TurnReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.TurnReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static protogalaxy.tictactoe.proto.TurnReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return new Builder(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(protogalaxy.tictactoe.proto.TurnReply prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tictactoe.TurnReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tictactoe.TurnReply)
      protogalaxy.tictactoe.proto.TurnReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_TurnReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_TurnReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protogalaxy.tictactoe.proto.TurnReply.class, protogalaxy.tictactoe.proto.TurnReply.Builder.class);
    }

    // Construct using protogalaxy.tictactoe.proto.TurnReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      status_ = 0;

      moveId_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_TurnReply_descriptor;
    }

    public protogalaxy.tictactoe.proto.TurnReply getDefaultInstanceForType() {
      return protogalaxy.tictactoe.proto.TurnReply.getDefaultInstance();
    }

    public protogalaxy.tictactoe.proto.TurnReply build() {
      protogalaxy.tictactoe.proto.TurnReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public protogalaxy.tictactoe.proto.TurnReply buildPartial() {
      protogalaxy.tictactoe.proto.TurnReply result = new protogalaxy.tictactoe.proto.TurnReply(this);
      result.status_ = status_;
      result.moveId_ = moveId_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protogalaxy.tictactoe.proto.TurnReply) {
        return mergeFrom((protogalaxy.tictactoe.proto.TurnReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protogalaxy.tictactoe.proto.TurnReply other) {
      if (other == protogalaxy.tictactoe.proto.TurnReply.getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getMoveId() != 0L) {
        setMoveId(other.getMoveId());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protogalaxy.tictactoe.proto.TurnReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protogalaxy.tictactoe.proto.TurnReply) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int status_ = 0;
    /**
     * <code>optional .tictactoe.TurnReply.ResponseStatus status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>optional .tictactoe.TurnReply.ResponseStatus status = 1;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .tictactoe.TurnReply.ResponseStatus status = 1;</code>
     */
    public protogalaxy.tictactoe.proto.TurnReply.ResponseStatus getStatus() {
      protogalaxy.tictactoe.proto.TurnReply.ResponseStatus result = protogalaxy.tictactoe.proto.TurnReply.ResponseStatus.valueOf(status_);
      return result == null ? protogalaxy.tictactoe.proto.TurnReply.ResponseStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .tictactoe.TurnReply.ResponseStatus status = 1;</code>
     */
    public Builder setStatus(protogalaxy.tictactoe.proto.TurnReply.ResponseStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .tictactoe.TurnReply.ResponseStatus status = 1;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private long moveId_ ;
    /**
     * <code>optional int64 move_id = 2;</code>
     */
    public long getMoveId() {
      return moveId_;
    }
    /**
     * <code>optional int64 move_id = 2;</code>
     */
    public Builder setMoveId(long value) {
      
      moveId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 move_id = 2;</code>
     */
    public Builder clearMoveId() {
      
      moveId_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tictactoe.TurnReply)
  }

  // @@protoc_insertion_point(class_scope:tictactoe.TurnReply)
  private static final protogalaxy.tictactoe.proto.TurnReply defaultInstance;static {
    defaultInstance = new protogalaxy.tictactoe.proto.TurnReply();
  }

  public static protogalaxy.tictactoe.proto.TurnReply getDefaultInstance() {
    return defaultInstance;
  }

  public protogalaxy.tictactoe.proto.TurnReply getDefaultInstanceForType() {
    return defaultInstance;
  }

}

