// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tictactoe.proto

package protogalaxy.tictactoe.proto;

/**
 * Protobuf type {@code tictactoe.TurnRequest}
 */
public  final class TurnRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tictactoe.TurnRequest)
    TurnRequestOrBuilder {
  // Use TurnRequest.newBuilder() to construct.
  private TurnRequest(com.google.protobuf.GeneratedMessage.Builder builder) {
    super(builder);
  }
  private TurnRequest() {
    gameId_ = "";
    userId_ = "";
    moveId_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TurnRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();

            gameId_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();

            userId_ = bs;
            break;
          }
          case 24: {

            moveId_ = input.readInt64();
            break;
          }
          case 34: {
            protogalaxy.tictactoe.proto.TurnRequest.Square.Builder subBuilder = null;
            if (move_ != null) {
              subBuilder = move_.toBuilder();
            }
            move_ = input.readMessage(protogalaxy.tictactoe.proto.TurnRequest.Square.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(move_);
              move_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_TurnRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_TurnRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protogalaxy.tictactoe.proto.TurnRequest.class, protogalaxy.tictactoe.proto.TurnRequest.Builder.class);
  }

  public static final com.google.protobuf.Parser<TurnRequest> PARSER =
      new com.google.protobuf.AbstractParser<TurnRequest>() {
    public TurnRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TurnRequest(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<TurnRequest> getParserForType() {
    return PARSER;
  }

  public interface SquareOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tictactoe.TurnRequest.Square)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 x = 1;</code>
     */
    int getX();

    /**
     * <code>optional int32 y = 2;</code>
     */
    int getY();
  }
  /**
   * Protobuf type {@code tictactoe.TurnRequest.Square}
   */
  public  static final class Square extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tictactoe.TurnRequest.Square)
      SquareOrBuilder {
    // Use Square.newBuilder() to construct.
    private Square(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private Square() {
      x_ = 0;
      y_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Square(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              x_ = input.readInt32();
              break;
            }
            case 16: {

              y_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_TurnRequest_Square_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_TurnRequest_Square_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protogalaxy.tictactoe.proto.TurnRequest.Square.class, protogalaxy.tictactoe.proto.TurnRequest.Square.Builder.class);
    }

    public static final com.google.protobuf.Parser<Square> PARSER =
        new com.google.protobuf.AbstractParser<Square>() {
      public Square parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Square(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Square> getParserForType() {
      return PARSER;
    }

    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>optional int32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>optional int32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (x_ != 0) {
        output.writeInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeInt32(2, y_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static protogalaxy.tictactoe.proto.TurnRequest.Square parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protogalaxy.tictactoe.proto.TurnRequest.Square parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protogalaxy.tictactoe.proto.TurnRequest.Square parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protogalaxy.tictactoe.proto.TurnRequest.Square parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protogalaxy.tictactoe.proto.TurnRequest.Square parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protogalaxy.tictactoe.proto.TurnRequest.Square parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protogalaxy.tictactoe.proto.TurnRequest.Square parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protogalaxy.tictactoe.proto.TurnRequest.Square parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protogalaxy.tictactoe.proto.TurnRequest.Square parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protogalaxy.tictactoe.proto.TurnRequest.Square parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protogalaxy.tictactoe.proto.TurnRequest.Square prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tictactoe.TurnRequest.Square}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tictactoe.TurnRequest.Square)
        protogalaxy.tictactoe.proto.TurnRequest.SquareOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_TurnRequest_Square_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_TurnRequest_Square_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protogalaxy.tictactoe.proto.TurnRequest.Square.class, protogalaxy.tictactoe.proto.TurnRequest.Square.Builder.class);
      }

      // Construct using protogalaxy.tictactoe.proto.TurnRequest.Square.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = 0;

        y_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_TurnRequest_Square_descriptor;
      }

      public protogalaxy.tictactoe.proto.TurnRequest.Square getDefaultInstanceForType() {
        return protogalaxy.tictactoe.proto.TurnRequest.Square.getDefaultInstance();
      }

      public protogalaxy.tictactoe.proto.TurnRequest.Square build() {
        protogalaxy.tictactoe.proto.TurnRequest.Square result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protogalaxy.tictactoe.proto.TurnRequest.Square buildPartial() {
        protogalaxy.tictactoe.proto.TurnRequest.Square result = new protogalaxy.tictactoe.proto.TurnRequest.Square(this);
        result.x_ = x_;
        result.y_ = y_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protogalaxy.tictactoe.proto.TurnRequest.Square) {
          return mergeFrom((protogalaxy.tictactoe.proto.TurnRequest.Square)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protogalaxy.tictactoe.proto.TurnRequest.Square other) {
        if (other == protogalaxy.tictactoe.proto.TurnRequest.Square.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protogalaxy.tictactoe.proto.TurnRequest.Square parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protogalaxy.tictactoe.proto.TurnRequest.Square) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int x_ ;
      /**
       * <code>optional int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder setX(int value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>optional int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder setY(int value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tictactoe.TurnRequest.Square)
    }

    // @@protoc_insertion_point(class_scope:tictactoe.TurnRequest.Square)
    private static final protogalaxy.tictactoe.proto.TurnRequest.Square defaultInstance;static {
      defaultInstance = new protogalaxy.tictactoe.proto.TurnRequest.Square();
    }

    public static protogalaxy.tictactoe.proto.TurnRequest.Square getDefaultInstance() {
      return defaultInstance;
    }

    public protogalaxy.tictactoe.proto.TurnRequest.Square getDefaultInstanceForType() {
      return defaultInstance;
    }

  }

  public static final int GAME_ID_FIELD_NUMBER = 1;
  private java.lang.Object gameId_;
  /**
   * <code>optional string game_id = 1;</code>
   */
  public java.lang.String getGameId() {
    java.lang.Object ref = gameId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        gameId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string game_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getGameIdBytes() {
    java.lang.Object ref = gameId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_ID_FIELD_NUMBER = 2;
  private java.lang.Object userId_;
  /**
   * <code>optional string user_id = 2;</code>
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        userId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string user_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MOVE_ID_FIELD_NUMBER = 3;
  private long moveId_;
  /**
   * <code>optional int64 move_id = 3;</code>
   */
  public long getMoveId() {
    return moveId_;
  }

  public static final int MOVE_FIELD_NUMBER = 4;
  private protogalaxy.tictactoe.proto.TurnRequest.Square move_;
  /**
   * <code>optional .tictactoe.TurnRequest.Square move = 4;</code>
   */
  public boolean hasMove() {
    return move_ != null;
  }
  /**
   * <code>optional .tictactoe.TurnRequest.Square move = 4;</code>
   */
  public protogalaxy.tictactoe.proto.TurnRequest.Square getMove() {
    return move_ == null ? protogalaxy.tictactoe.proto.TurnRequest.Square.getDefaultInstance() : move_;
  }
  /**
   * <code>optional .tictactoe.TurnRequest.Square move = 4;</code>
   */
  public protogalaxy.tictactoe.proto.TurnRequest.SquareOrBuilder getMoveOrBuilder() {
    return getMove();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getGameIdBytes().isEmpty()) {
      output.writeBytes(1, getGameIdBytes());
    }
    if (!getUserIdBytes().isEmpty()) {
      output.writeBytes(2, getUserIdBytes());
    }
    if (moveId_ != 0L) {
      output.writeInt64(3, moveId_);
    }
    if (move_ != null) {
      output.writeMessage(4, getMove());
    }
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!getGameIdBytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getGameIdBytes());
    }
    if (!getUserIdBytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getUserIdBytes());
    }
    if (moveId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, moveId_);
    }
    if (move_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getMove());
    }
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static protogalaxy.tictactoe.proto.TurnRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protogalaxy.tictactoe.proto.TurnRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.TurnRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protogalaxy.tictactoe.proto.TurnRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.TurnRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static protogalaxy.tictactoe.proto.TurnRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.TurnRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static protogalaxy.tictactoe.proto.TurnRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.TurnRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static protogalaxy.tictactoe.proto.TurnRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return new Builder(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(protogalaxy.tictactoe.proto.TurnRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tictactoe.TurnRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tictactoe.TurnRequest)
      protogalaxy.tictactoe.proto.TurnRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_TurnRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_TurnRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protogalaxy.tictactoe.proto.TurnRequest.class, protogalaxy.tictactoe.proto.TurnRequest.Builder.class);
    }

    // Construct using protogalaxy.tictactoe.proto.TurnRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      gameId_ = "";

      userId_ = "";

      moveId_ = 0L;

      if (moveBuilder_ == null) {
        move_ = null;
      } else {
        move_ = null;
        moveBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_TurnRequest_descriptor;
    }

    public protogalaxy.tictactoe.proto.TurnRequest getDefaultInstanceForType() {
      return protogalaxy.tictactoe.proto.TurnRequest.getDefaultInstance();
    }

    public protogalaxy.tictactoe.proto.TurnRequest build() {
      protogalaxy.tictactoe.proto.TurnRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public protogalaxy.tictactoe.proto.TurnRequest buildPartial() {
      protogalaxy.tictactoe.proto.TurnRequest result = new protogalaxy.tictactoe.proto.TurnRequest(this);
      result.gameId_ = gameId_;
      result.userId_ = userId_;
      result.moveId_ = moveId_;
      if (moveBuilder_ == null) {
        result.move_ = move_;
      } else {
        result.move_ = moveBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protogalaxy.tictactoe.proto.TurnRequest) {
        return mergeFrom((protogalaxy.tictactoe.proto.TurnRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protogalaxy.tictactoe.proto.TurnRequest other) {
      if (other == protogalaxy.tictactoe.proto.TurnRequest.getDefaultInstance()) return this;
      if (!other.getGameId().isEmpty()) {
        gameId_ = other.gameId_;
        onChanged();
      }
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (other.getMoveId() != 0L) {
        setMoveId(other.getMoveId());
      }
      if (other.hasMove()) {
        mergeMove(other.getMove());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protogalaxy.tictactoe.proto.TurnRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protogalaxy.tictactoe.proto.TurnRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object gameId_ = "";
    /**
     * <code>optional string game_id = 1;</code>
     */
    public java.lang.String getGameId() {
      java.lang.Object ref = gameId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gameId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string game_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGameIdBytes() {
      java.lang.Object ref = gameId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string game_id = 1;</code>
     */
    public Builder setGameId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gameId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string game_id = 1;</code>
     */
    public Builder clearGameId() {
      
      gameId_ = getDefaultInstance().getGameId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string game_id = 1;</code>
     */
    public Builder setGameIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gameId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <code>optional string user_id = 2;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string user_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string user_id = 2;</code>
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string user_id = 2;</code>
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string user_id = 2;</code>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }

    private long moveId_ ;
    /**
     * <code>optional int64 move_id = 3;</code>
     */
    public long getMoveId() {
      return moveId_;
    }
    /**
     * <code>optional int64 move_id = 3;</code>
     */
    public Builder setMoveId(long value) {
      
      moveId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 move_id = 3;</code>
     */
    public Builder clearMoveId() {
      
      moveId_ = 0L;
      onChanged();
      return this;
    }

    private protogalaxy.tictactoe.proto.TurnRequest.Square move_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        protogalaxy.tictactoe.proto.TurnRequest.Square, protogalaxy.tictactoe.proto.TurnRequest.Square.Builder, protogalaxy.tictactoe.proto.TurnRequest.SquareOrBuilder> moveBuilder_;
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 4;</code>
     */
    public boolean hasMove() {
      return moveBuilder_ != null || move_ != null;
    }
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 4;</code>
     */
    public protogalaxy.tictactoe.proto.TurnRequest.Square getMove() {
      if (moveBuilder_ == null) {
        return move_ == null ? protogalaxy.tictactoe.proto.TurnRequest.Square.getDefaultInstance() : move_;
      } else {
        return moveBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 4;</code>
     */
    public Builder setMove(protogalaxy.tictactoe.proto.TurnRequest.Square value) {
      if (moveBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        move_ = value;
        onChanged();
      } else {
        moveBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 4;</code>
     */
    public Builder setMove(
        protogalaxy.tictactoe.proto.TurnRequest.Square.Builder builderForValue) {
      if (moveBuilder_ == null) {
        move_ = builderForValue.build();
        onChanged();
      } else {
        moveBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 4;</code>
     */
    public Builder mergeMove(protogalaxy.tictactoe.proto.TurnRequest.Square value) {
      if (moveBuilder_ == null) {
        if (move_ != null) {
          move_ =
            protogalaxy.tictactoe.proto.TurnRequest.Square.newBuilder(move_).mergeFrom(value).buildPartial();
        } else {
          move_ = value;
        }
        onChanged();
      } else {
        moveBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 4;</code>
     */
    public Builder clearMove() {
      if (moveBuilder_ == null) {
        move_ = null;
        onChanged();
      } else {
        move_ = null;
        moveBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 4;</code>
     */
    public protogalaxy.tictactoe.proto.TurnRequest.Square.Builder getMoveBuilder() {
      
      onChanged();
      return getMoveFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 4;</code>
     */
    public protogalaxy.tictactoe.proto.TurnRequest.SquareOrBuilder getMoveOrBuilder() {
      if (moveBuilder_ != null) {
        return moveBuilder_.getMessageOrBuilder();
      } else {
        return move_ == null ?
            protogalaxy.tictactoe.proto.TurnRequest.Square.getDefaultInstance() : move_;
      }
    }
    /**
     * <code>optional .tictactoe.TurnRequest.Square move = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        protogalaxy.tictactoe.proto.TurnRequest.Square, protogalaxy.tictactoe.proto.TurnRequest.Square.Builder, protogalaxy.tictactoe.proto.TurnRequest.SquareOrBuilder> 
        getMoveFieldBuilder() {
      if (moveBuilder_ == null) {
        moveBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            protogalaxy.tictactoe.proto.TurnRequest.Square, protogalaxy.tictactoe.proto.TurnRequest.Square.Builder, protogalaxy.tictactoe.proto.TurnRequest.SquareOrBuilder>(
                getMove(),
                getParentForChildren(),
                isClean());
        move_ = null;
      }
      return moveBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tictactoe.TurnRequest)
  }

  // @@protoc_insertion_point(class_scope:tictactoe.TurnRequest)
  private static final protogalaxy.tictactoe.proto.TurnRequest defaultInstance;static {
    defaultInstance = new protogalaxy.tictactoe.proto.TurnRequest();
  }

  public static protogalaxy.tictactoe.proto.TurnRequest getDefaultInstance() {
    return defaultInstance;
  }

  public protogalaxy.tictactoe.proto.TurnRequest getDefaultInstanceForType() {
    return defaultInstance;
  }

}

