// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tictactoe.proto

package protogalaxy.tictactoe.proto;

public interface WinnerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tictactoe.JsonWinner)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool draw = 1;</code>
   */
  boolean getDraw();

  /**
   * <code>optional string user_id = 2;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>optional string user_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
   */
  java.util.List<protogalaxy.tictactoe.proto.Winner.Location>
      getLocationsList();
  /**
   * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
   */
  protogalaxy.tictactoe.proto.Winner.Location getLocations(int index);
  /**
   * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
   */
  int getLocationsCount();
  /**
   * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
   */
  java.util.List<? extends protogalaxy.tictactoe.proto.Winner.LocationOrBuilder>
      getLocationsOrBuilderList();
  /**
   * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
   */
  protogalaxy.tictactoe.proto.Winner.LocationOrBuilder getLocationsOrBuilder(
      int index);
}
