// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tictactoe.proto

package protogalaxy.tictactoe.proto;

/**
 * Protobuf type {@code tictactoe.JsonWinner}
 */
public  final class Winner extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tictactoe.JsonWinner)
    WinnerOrBuilder {
  // Use JsonWinner.newBuilder() to construct.
  private Winner(com.google.protobuf.GeneratedMessage.Builder builder) {
    super(builder);
  }
  private Winner() {
    locations_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Winner(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            winnerStatusCase_ = 1;
            winnerStatus_ = input.readBool();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            winnerStatusCase_ = 2;
            winnerStatus_ = bs;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              locations_ = new java.util.ArrayList<protogalaxy.tictactoe.proto.Winner.Location>();
              mutable_bitField0_ |= 0x00000004;
            }
            locations_.add(input.readMessage(protogalaxy.tictactoe.proto.Winner.Location.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        locations_ = java.util.Collections.unmodifiableList(locations_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_Winner_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_Winner_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protogalaxy.tictactoe.proto.Winner.class, protogalaxy.tictactoe.proto.Winner.Builder.class);
  }

  public static final com.google.protobuf.Parser<Winner> PARSER =
      new com.google.protobuf.AbstractParser<Winner>() {
    public Winner parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Winner(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Winner> getParserForType() {
    return PARSER;
  }

  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tictactoe.JsonWinner.JsonLocation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .tictactoe.JsonWinner.JsonLocation.Direction direction = 1;</code>
     */
    int getDirectionValue();
    /**
     * <code>optional .tictactoe.JsonWinner.JsonLocation.Direction direction = 1;</code>
     */
    protogalaxy.tictactoe.proto.Winner.Location.Direction getDirection();

    /**
     * <code>optional int32 position = 2;</code>
     */
    int getPosition();
  }
  /**
   * Protobuf type {@code tictactoe.JsonWinner.JsonLocation}
   */
  public  static final class Location extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tictactoe.JsonWinner.JsonLocation)
      LocationOrBuilder {
    // Use JsonLocation.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private Location() {
      direction_ = 0;
      position_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Location(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              direction_ = rawValue;
              break;
            }
            case 16: {

              position_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_Winner_Location_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_Winner_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protogalaxy.tictactoe.proto.Winner.Location.class, protogalaxy.tictactoe.proto.Winner.Location.Builder.class);
    }

    public static final com.google.protobuf.Parser<Location> PARSER =
        new com.google.protobuf.AbstractParser<Location>() {
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Location(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code tictactoe.JsonWinner.JsonLocation.Direction}
     */
    public enum Direction
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HORIZONTAL = 0;</code>
       */
      HORIZONTAL(0, 0),
      /**
       * <code>VERTICAL = 1;</code>
       */
      VERTICAL(1, 1),
      /**
       * <code>DIAGONAL_DOWN = 2;</code>
       */
      DIAGONAL_DOWN(2, 2),
      /**
       * <code>DIAGONAL_UP = 3;</code>
       */
      DIAGONAL_UP(3, 3),
      UNRECOGNIZED(-1, -1),
      ;

      /**
       * <code>HORIZONTAL = 0;</code>
       */
      public static final int HORIZONTAL_VALUE = 0;
      /**
       * <code>VERTICAL = 1;</code>
       */
      public static final int VERTICAL_VALUE = 1;
      /**
       * <code>DIAGONAL_DOWN = 2;</code>
       */
      public static final int DIAGONAL_DOWN_VALUE = 2;
      /**
       * <code>DIAGONAL_UP = 3;</code>
       */
      public static final int DIAGONAL_UP_VALUE = 3;


      public final int getNumber() {
        if (index == -1) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      public static Direction valueOf(int value) {
        switch (value) {
          case 0: return HORIZONTAL;
          case 1: return VERTICAL;
          case 2: return DIAGONAL_DOWN;
          case 3: return DIAGONAL_UP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Direction>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Direction>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Direction>() {
              public Direction findValueByNumber(int number) {
                return Direction.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protogalaxy.tictactoe.proto.Winner.Location.getDescriptor().getEnumTypes().get(0);
      }

      private static final Direction[] VALUES = values();

      public static Direction valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Direction(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tictactoe.JsonWinner.JsonLocation.Direction)
    }

    public static final int DIRECTION_FIELD_NUMBER = 1;
    private int direction_;
    /**
     * <code>optional .tictactoe.JsonWinner.JsonLocation.Direction direction = 1;</code>
     */
    public int getDirectionValue() {
      return direction_;
    }
    /**
     * <code>optional .tictactoe.JsonWinner.JsonLocation.Direction direction = 1;</code>
     */
    public protogalaxy.tictactoe.proto.Winner.Location.Direction getDirection() {
      protogalaxy.tictactoe.proto.Winner.Location.Direction result = protogalaxy.tictactoe.proto.Winner.Location.Direction.valueOf(direction_);
      return result == null ? protogalaxy.tictactoe.proto.Winner.Location.Direction.UNRECOGNIZED : result;
    }

    public static final int POSITION_FIELD_NUMBER = 2;
    private int position_;
    /**
     * <code>optional int32 position = 2;</code>
     */
    public int getPosition() {
      return position_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (direction_ != protogalaxy.tictactoe.proto.Winner.Location.Direction.HORIZONTAL.getNumber()) {
        output.writeEnum(1, direction_);
      }
      if (position_ != 0) {
        output.writeInt32(2, position_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (direction_ != protogalaxy.tictactoe.proto.Winner.Location.Direction.HORIZONTAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, direction_);
      }
      if (position_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, position_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static protogalaxy.tictactoe.proto.Winner.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protogalaxy.tictactoe.proto.Winner.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protogalaxy.tictactoe.proto.Winner.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protogalaxy.tictactoe.proto.Winner.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protogalaxy.tictactoe.proto.Winner.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protogalaxy.tictactoe.proto.Winner.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protogalaxy.tictactoe.proto.Winner.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protogalaxy.tictactoe.proto.Winner.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protogalaxy.tictactoe.proto.Winner.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protogalaxy.tictactoe.proto.Winner.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protogalaxy.tictactoe.proto.Winner.Location prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tictactoe.JsonWinner.JsonLocation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tictactoe.JsonWinner.JsonLocation)
        protogalaxy.tictactoe.proto.Winner.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_Winner_Location_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_Winner_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protogalaxy.tictactoe.proto.Winner.Location.class, protogalaxy.tictactoe.proto.Winner.Location.Builder.class);
      }

      // Construct using protogalaxy.tictactoe.proto.JsonWinner.JsonLocation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        direction_ = 0;

        position_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_Winner_Location_descriptor;
      }

      public protogalaxy.tictactoe.proto.Winner.Location getDefaultInstanceForType() {
        return protogalaxy.tictactoe.proto.Winner.Location.getDefaultInstance();
      }

      public protogalaxy.tictactoe.proto.Winner.Location build() {
        protogalaxy.tictactoe.proto.Winner.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protogalaxy.tictactoe.proto.Winner.Location buildPartial() {
        protogalaxy.tictactoe.proto.Winner.Location result = new protogalaxy.tictactoe.proto.Winner.Location(this);
        result.direction_ = direction_;
        result.position_ = position_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protogalaxy.tictactoe.proto.Winner.Location) {
          return mergeFrom((protogalaxy.tictactoe.proto.Winner.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protogalaxy.tictactoe.proto.Winner.Location other) {
        if (other == protogalaxy.tictactoe.proto.Winner.Location.getDefaultInstance()) return this;
        if (other.direction_ != 0) {
          setDirectionValue(other.getDirectionValue());
        }
        if (other.getPosition() != 0) {
          setPosition(other.getPosition());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protogalaxy.tictactoe.proto.Winner.Location parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protogalaxy.tictactoe.proto.Winner.Location) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int direction_ = 0;
      /**
       * <code>optional .tictactoe.JsonWinner.JsonLocation.Direction direction = 1;</code>
       */
      public int getDirectionValue() {
        return direction_;
      }
      /**
       * <code>optional .tictactoe.JsonWinner.JsonLocation.Direction direction = 1;</code>
       */
      public Builder setDirectionValue(int value) {
        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .tictactoe.JsonWinner.JsonLocation.Direction direction = 1;</code>
       */
      public protogalaxy.tictactoe.proto.Winner.Location.Direction getDirection() {
        protogalaxy.tictactoe.proto.Winner.Location.Direction result = protogalaxy.tictactoe.proto.Winner.Location.Direction.valueOf(direction_);
        return result == null ? protogalaxy.tictactoe.proto.Winner.Location.Direction.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .tictactoe.JsonWinner.JsonLocation.Direction direction = 1;</code>
       */
      public Builder setDirection(protogalaxy.tictactoe.proto.Winner.Location.Direction value) {
        if (value == null) {
          throw new NullPointerException();
        }

        direction_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .tictactoe.JsonWinner.JsonLocation.Direction direction = 1;</code>
       */
      public Builder clearDirection() {

        direction_ = 0;
        onChanged();
        return this;
      }

      private int position_ ;
      /**
       * <code>optional int32 position = 2;</code>
       */
      public int getPosition() {
        return position_;
      }
      /**
       * <code>optional int32 position = 2;</code>
       */
      public Builder setPosition(int value) {

        position_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 position = 2;</code>
       */
      public Builder clearPosition() {

        position_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tictactoe.JsonWinner.JsonLocation)
    }

    // @@protoc_insertion_point(class_scope:tictactoe.JsonWinner.JsonLocation)
    private static final protogalaxy.tictactoe.proto.Winner.Location defaultInstance;static {
      defaultInstance = new protogalaxy.tictactoe.proto.Winner.Location();
    }

    public static protogalaxy.tictactoe.proto.Winner.Location getDefaultInstance() {
      return defaultInstance;
    }

    public protogalaxy.tictactoe.proto.Winner.Location getDefaultInstanceForType() {
      return defaultInstance;
    }

  }

  private int bitField0_;
  private int winnerStatusCase_ = 0;
  private java.lang.Object winnerStatus_;
  public enum WinnerStatusCase
      implements com.google.protobuf.Internal.EnumLite {
    DRAW(1),
    USER_ID(2),
    WINNERSTATUS_NOT_SET(0);
    private int value = 0;
    private WinnerStatusCase(int value) {
      this.value = value;
    }
    public static WinnerStatusCase valueOf(int value) {
      switch (value) {
        case 1: return DRAW;
        case 2: return USER_ID;
        case 0: return WINNERSTATUS_NOT_SET;
        default: throw new java.lang.IllegalArgumentException(
          "Value is undefined for this oneof enum.");
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public WinnerStatusCase
  getWinnerStatusCase() {
    return WinnerStatusCase.valueOf(
        winnerStatusCase_);
  }

  public static final int DRAW_FIELD_NUMBER = 1;
  /**
   * <code>optional bool draw = 1;</code>
   */
  public boolean getDraw() {
    if (winnerStatusCase_ == 1) {
      return (java.lang.Boolean) winnerStatus_;
    }
    return false;
  }

  public static final int USER_ID_FIELD_NUMBER = 2;
  /**
   * <code>optional string user_id = 2;</code>
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = "";
    if (winnerStatusCase_ == 2) {
      ref = winnerStatus_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8() && (winnerStatusCase_ == 2)) {
        winnerStatus_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string user_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = "";
    if (winnerStatusCase_ == 2) {
      ref = winnerStatus_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (winnerStatusCase_ == 2) {
        winnerStatus_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCATIONS_FIELD_NUMBER = 3;
  private java.util.List<protogalaxy.tictactoe.proto.Winner.Location> locations_;
  /**
   * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
   */
  public java.util.List<protogalaxy.tictactoe.proto.Winner.Location> getLocationsList() {
    return locations_;
  }
  /**
   * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
   */
  public java.util.List<? extends protogalaxy.tictactoe.proto.Winner.LocationOrBuilder>
      getLocationsOrBuilderList() {
    return locations_;
  }
  /**
   * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
   */
  public int getLocationsCount() {
    return locations_.size();
  }
  /**
   * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
   */
  public protogalaxy.tictactoe.proto.Winner.Location getLocations(int index) {
    return locations_.get(index);
  }
  /**
   * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
   */
  public protogalaxy.tictactoe.proto.Winner.LocationOrBuilder getLocationsOrBuilder(
      int index) {
    return locations_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (winnerStatusCase_ == 1) {
      output.writeBool(
          1, (boolean)((java.lang.Boolean) winnerStatus_));
    }
    if (winnerStatusCase_ == 2) {
      output.writeBytes(2, getUserIdBytes());
    }
    for (int i = 0; i < locations_.size(); i++) {
      output.writeMessage(3, locations_.get(i));
    }
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (winnerStatusCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            1, (boolean)((java.lang.Boolean) winnerStatus_));
    }
    if (winnerStatusCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getUserIdBytes());
    }
    for (int i = 0; i < locations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, locations_.get(i));
    }
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static protogalaxy.tictactoe.proto.Winner parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protogalaxy.tictactoe.proto.Winner parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.Winner parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protogalaxy.tictactoe.proto.Winner parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.Winner parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static protogalaxy.tictactoe.proto.Winner parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.Winner parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static protogalaxy.tictactoe.proto.Winner parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static protogalaxy.tictactoe.proto.Winner parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static protogalaxy.tictactoe.proto.Winner parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return new Builder(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(protogalaxy.tictactoe.proto.Winner prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tictactoe.JsonWinner}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tictactoe.JsonWinner)
      protogalaxy.tictactoe.proto.WinnerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_Winner_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_Winner_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protogalaxy.tictactoe.proto.Winner.class, protogalaxy.tictactoe.proto.Winner.Builder.class);
    }

    // Construct using protogalaxy.tictactoe.proto.JsonWinner.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getLocationsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (locationsBuilder_ == null) {
        locations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        locationsBuilder_.clear();
      }
      winnerStatusCase_ = 0;
      winnerStatus_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protogalaxy.tictactoe.proto.Tictactoe.internal_static_tictactoe_Winner_descriptor;
    }

    public protogalaxy.tictactoe.proto.Winner getDefaultInstanceForType() {
      return protogalaxy.tictactoe.proto.Winner.getDefaultInstance();
    }

    public protogalaxy.tictactoe.proto.Winner build() {
      protogalaxy.tictactoe.proto.Winner result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public protogalaxy.tictactoe.proto.Winner buildPartial() {
      protogalaxy.tictactoe.proto.Winner result = new protogalaxy.tictactoe.proto.Winner(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (winnerStatusCase_ == 1) {
        result.winnerStatus_ = winnerStatus_;
      }
      if (winnerStatusCase_ == 2) {
        result.winnerStatus_ = winnerStatus_;
      }
      if (locationsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          locations_ = java.util.Collections.unmodifiableList(locations_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.locations_ = locations_;
      } else {
        result.locations_ = locationsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      result.winnerStatusCase_ = winnerStatusCase_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protogalaxy.tictactoe.proto.Winner) {
        return mergeFrom((protogalaxy.tictactoe.proto.Winner)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protogalaxy.tictactoe.proto.Winner other) {
      if (other == protogalaxy.tictactoe.proto.Winner.getDefaultInstance()) return this;
      if (locationsBuilder_ == null) {
        if (!other.locations_.isEmpty()) {
          if (locations_.isEmpty()) {
            locations_ = other.locations_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureLocationsIsMutable();
            locations_.addAll(other.locations_);
          }
          onChanged();
        }
      } else {
        if (!other.locations_.isEmpty()) {
          if (locationsBuilder_.isEmpty()) {
            locationsBuilder_.dispose();
            locationsBuilder_ = null;
            locations_ = other.locations_;
            bitField0_ = (bitField0_ & ~0x00000004);
            locationsBuilder_ =
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getLocationsFieldBuilder() : null;
          } else {
            locationsBuilder_.addAllMessages(other.locations_);
          }
        }
      }
      switch (other.getWinnerStatusCase()) {
        case DRAW: {
          setDraw(other.getDraw());
          break;
        }
        case USER_ID: {
          winnerStatusCase_ = 2;
          winnerStatus_ = other.winnerStatus_;
          onChanged();
          break;
        }
        case WINNERSTATUS_NOT_SET: {
          break;
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protogalaxy.tictactoe.proto.Winner parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protogalaxy.tictactoe.proto.Winner) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int winnerStatusCase_ = 0;
    private java.lang.Object winnerStatus_;
    public WinnerStatusCase
        getWinnerStatusCase() {
      return WinnerStatusCase.valueOf(
          winnerStatusCase_);
    }

    public Builder clearWinnerStatus() {
      winnerStatusCase_ = 0;
      winnerStatus_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <code>optional bool draw = 1;</code>
     */
    public boolean getDraw() {
      if (winnerStatusCase_ == 1) {
        return (java.lang.Boolean) winnerStatus_;
      }
      return false;
    }
    /**
     * <code>optional bool draw = 1;</code>
     */
    public Builder setDraw(boolean value) {
      winnerStatusCase_ = 1;
      winnerStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool draw = 1;</code>
     */
    public Builder clearDraw() {
      if (winnerStatusCase_ == 1) {
        winnerStatusCase_ = 0;
        winnerStatus_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>optional string user_id = 2;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = "";
      if (winnerStatusCase_ == 2) {
        ref = winnerStatus_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (winnerStatusCase_ == 2) {
          if (bs.isValidUtf8()) {
            winnerStatus_ = s;
          }
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string user_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = "";
      if (winnerStatusCase_ == 2) {
        ref = winnerStatus_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (winnerStatusCase_ == 2) {
          winnerStatus_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string user_id = 2;</code>
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  winnerStatusCase_ = 2;
      winnerStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string user_id = 2;</code>
     */
    public Builder clearUserId() {
      if (winnerStatusCase_ == 2) {
        winnerStatusCase_ = 0;
        winnerStatus_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional string user_id = 2;</code>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  winnerStatusCase_ = 2;
      winnerStatus_ = value;
      onChanged();
      return this;
    }

    private java.util.List<protogalaxy.tictactoe.proto.Winner.Location> locations_ =
      java.util.Collections.emptyList();
    private void ensureLocationsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        locations_ = new java.util.ArrayList<protogalaxy.tictactoe.proto.Winner.Location>(locations_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        protogalaxy.tictactoe.proto.Winner.Location, protogalaxy.tictactoe.proto.Winner.Location.Builder, protogalaxy.tictactoe.proto.Winner.LocationOrBuilder> locationsBuilder_;

    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public java.util.List<protogalaxy.tictactoe.proto.Winner.Location> getLocationsList() {
      if (locationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(locations_);
      } else {
        return locationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public int getLocationsCount() {
      if (locationsBuilder_ == null) {
        return locations_.size();
      } else {
        return locationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public protogalaxy.tictactoe.proto.Winner.Location getLocations(int index) {
      if (locationsBuilder_ == null) {
        return locations_.get(index);
      } else {
        return locationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public Builder setLocations(
        int index, protogalaxy.tictactoe.proto.Winner.Location value) {
      if (locationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationsIsMutable();
        locations_.set(index, value);
        onChanged();
      } else {
        locationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public Builder setLocations(
        int index, protogalaxy.tictactoe.proto.Winner.Location.Builder builderForValue) {
      if (locationsBuilder_ == null) {
        ensureLocationsIsMutable();
        locations_.set(index, builderForValue.build());
        onChanged();
      } else {
        locationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public Builder addLocations(protogalaxy.tictactoe.proto.Winner.Location value) {
      if (locationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationsIsMutable();
        locations_.add(value);
        onChanged();
      } else {
        locationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public Builder addLocations(
        int index, protogalaxy.tictactoe.proto.Winner.Location value) {
      if (locationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationsIsMutable();
        locations_.add(index, value);
        onChanged();
      } else {
        locationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public Builder addLocations(
        protogalaxy.tictactoe.proto.Winner.Location.Builder builderForValue) {
      if (locationsBuilder_ == null) {
        ensureLocationsIsMutable();
        locations_.add(builderForValue.build());
        onChanged();
      } else {
        locationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public Builder addLocations(
        int index, protogalaxy.tictactoe.proto.Winner.Location.Builder builderForValue) {
      if (locationsBuilder_ == null) {
        ensureLocationsIsMutable();
        locations_.add(index, builderForValue.build());
        onChanged();
      } else {
        locationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public Builder addAllLocations(
        java.lang.Iterable<? extends protogalaxy.tictactoe.proto.Winner.Location> values) {
      if (locationsBuilder_ == null) {
        ensureLocationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, locations_);
        onChanged();
      } else {
        locationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public Builder clearLocations() {
      if (locationsBuilder_ == null) {
        locations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        locationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public Builder removeLocations(int index) {
      if (locationsBuilder_ == null) {
        ensureLocationsIsMutable();
        locations_.remove(index);
        onChanged();
      } else {
        locationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public protogalaxy.tictactoe.proto.Winner.Location.Builder getLocationsBuilder(
        int index) {
      return getLocationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public protogalaxy.tictactoe.proto.Winner.LocationOrBuilder getLocationsOrBuilder(
        int index) {
      if (locationsBuilder_ == null) {
        return locations_.get(index);  } else {
        return locationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public java.util.List<? extends protogalaxy.tictactoe.proto.Winner.LocationOrBuilder>
         getLocationsOrBuilderList() {
      if (locationsBuilder_ != null) {
        return locationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(locations_);
      }
    }
    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public protogalaxy.tictactoe.proto.Winner.Location.Builder addLocationsBuilder() {
      return getLocationsFieldBuilder().addBuilder(
          protogalaxy.tictactoe.proto.Winner.Location.getDefaultInstance());
    }
    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public protogalaxy.tictactoe.proto.Winner.Location.Builder addLocationsBuilder(
        int index) {
      return getLocationsFieldBuilder().addBuilder(
          index, protogalaxy.tictactoe.proto.Winner.Location.getDefaultInstance());
    }
    /**
     * <code>repeated .tictactoe.JsonWinner.JsonLocation locations = 3;</code>
     */
    public java.util.List<protogalaxy.tictactoe.proto.Winner.Location.Builder>
         getLocationsBuilderList() {
      return getLocationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        protogalaxy.tictactoe.proto.Winner.Location, protogalaxy.tictactoe.proto.Winner.Location.Builder, protogalaxy.tictactoe.proto.Winner.LocationOrBuilder>
        getLocationsFieldBuilder() {
      if (locationsBuilder_ == null) {
        locationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            protogalaxy.tictactoe.proto.Winner.Location, protogalaxy.tictactoe.proto.Winner.Location.Builder, protogalaxy.tictactoe.proto.Winner.LocationOrBuilder>(
                locations_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        locations_ = null;
      }
      return locationsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tictactoe.JsonWinner)
  }

  // @@protoc_insertion_point(class_scope:tictactoe.JsonWinner)
  private static final protogalaxy.tictactoe.proto.Winner defaultInstance;static {
    defaultInstance = new protogalaxy.tictactoe.proto.Winner();
  }

  public static protogalaxy.tictactoe.proto.Winner getDefaultInstance() {
    return defaultInstance;
  }

  public protogalaxy.tictactoe.proto.Winner getDefaultInstanceForType() {
    return defaultInstance;
  }

}

